name: vanilla_state
description: A very simple way to manage immutable state in flutter without having too much dependencies
version: 0.0.1-alpha
homepage: https://github.com/folaoluwafemi/vanilla_state
repository: https://github.com/folaoluwafemi/vanilla_state



environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

